src/Ml.Cli.WebApp/ClientApp/src/Comparison/TableItem.js, src/Ml.Cli.WebApp/ClientApp/src/ImagesList/ImagesList.scss
=> fix(TableItem): configuration annotation button now opens and closes annotation components properly

src/Ml.Cli.WebApp/ClientApp/package-lock.json, src/Ml.Cli.WebApp/ClientApp/src/Annotation/AnnotationImagesLoader.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/Ocr/Ocr.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/__snapshots__/Annotate.spec.js.snap, src/Ml.Cli.WebApp/ClientApp/src/Annotation/__snapshots__/AnnotationImagesLoader.spec.js.snap, src/Ml.Cli.WebApp/ClientApp/src/Comparison/EditorTab.js
=> fix(Comparison): on-the-fly update of modified comparison item

README.md, src/Ml.Cli.WebApp/Program.cs
=> feat(Webapp): automatically add directory separator to base directory

src/Ml.Cli/JobApiCall/README.MD, src/Ml.Cli/JobCompare/README.MD, src/Ml.Cli/JobDataset/README.MD, src/Ml.Cli/JobLoop/README.MD, src/Ml.Cli/JobParallel/README.MD, src/Ml.Cli/JobScript/README.MD, src/Ml.Cli/JobSerial/README.MD, src/Ml.Cli/JobVersion/README.MD
=> docs(tasks): update readme for all tasks

src/Ml.Cli.WebApp/ClientApp/src/Comparison/JsonEditorTab.js, src/Ml.Cli.WebApp/Controllers/CompareController.cs, src/Ml.Cli.WebApp/Controllers/ComparesController.cs, tests/Ml.Cli.WebApp.Tests/ComparesControllerUnitTest.cs
=> refactor(Comparison): rename route api/compare as api/compares

README.md, src/Ml.Cli.WebApp/Ml.Cli.WebApp.csproj, src/Ml.Cli.WebApp/Program.cs, src/Ml.Cli.WebApp/Worker.cs, src/Ml.Cli/Ml.Cli.csproj, src/Ml.Cli/Program.cs
=> feat(WebApp): improve arguments description and usage

src/Ml.Cli.WebApp/ClientApp/src/Annotation/Annotate.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Annotate.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/__snapshots__/Annotate.spec.js.snap, src/Ml.Cli.WebApp/ClientApp/src/Comparison/Compare.js, src/Ml.Cli.WebApp/ClientApp/src/Comparison/__snapshots__/index.spec.js.snap, src/Ml.Cli.WebApp/ClientApp/src/Comparison/index.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Home.js, src/Ml.Cli.WebApp/ClientApp/src/TitleBar/TitleBar.js, src/Ml.Cli.WebApp/ClientApp/src/TitleBar/TitleBar.scss, src/Ml.Cli.WebApp/ClientApp/src/__snapshots__/Home.spec.js.snap
=> feat(TitleBar): add TitleBar component

demo/tasks-licenses.json, src/Ml.Cli.WebApp/ClientApp/src/Annotation/AnnotationImagesLoader.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/DatasetHandler.js, src/Ml.Cli.WebApp/Controllers/AnnotationsController.cs, src/Ml.Cli/JobDataset/DatasetResult.cs, src/Ml.Cli/JobDataset/DatasetTask.cs, src/Ml.Cli/JobDataset/Initializer.cs, src/Ml.Cli/JobDataset/Job.cs, src/Ml.Cli/JobDataset/README.MD, tests/Ml.Cli.Tests/JobsTests/DatasetUnitTest.cs
=> feat(Dataset): add frontDefaultStringsMatcher parameter to select webapp displayed images

src/Ml.Cli/JobCompare/Job.cs, src/Ml.Cli/JobCompare/README.MD, tests/Ml.Cli.Tests/JobsTests/ApiCallUnitTest.cs, tests/Ml.Cli.Tests/JobsTests/CompareUnitTest.cs, tests/Ml.Cli.Tests/JobsTests/DatasetUnitTest.cs, tests/Ml.Cli.Tests/JobsTests/ScriptUnitTest.cs, tests/Ml.Cli.Tests/JobsTests/VersionUnitTest.cs
=> feat(Compare): compare task now works with non-callapi files

src/Ml.Cli.WebApp/ClientApp/src/Annotation/AnnotationImagesLoader.js, src/Ml.Cli.WebApp/ClientApp/src/Comparison/JsonEditorTab.js, src/Ml.Cli.WebApp/Controllers/AnnotationsController.cs, src/Ml.Cli.WebApp/Controllers/ComparesController.cs, src/Ml.Cli.WebApp/Controllers/DatasetsController.cs
=> refactor(Controllers): remove "/save" from api routes

tests/Ml.Cli.WebApp.Tests/AnnotationsControllerUnitTest.cs, tests/Ml.Cli.WebApp.Tests/FilesControllerUnitTest.cs
=> test(controllers): add unit tests on annotations and files controllers

How-to-use-Ml-Cli-in-jupyterlab.md, Jupyterlab/ml-cli-jupyter-latest.md, Jupyterlab/ml-cli-jupyter.sh, Jupyterlab/ml-cli-launcher.sh
closes #85 
The .sh files were tested on JupyterLab environment.
=> Docs(ml cli jupyter): add readme for ml-cli jupyterlab installation and usage and add .sh files for jupyterlab usage

src/Ml.Cli.WebApp/ClientApp/src/Annotation/TableAnnotate.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/TableAnnotate.scss, src/Ml.Cli.WebApp/ClientApp/src/Annotation/__snapshots__/Annotate.spec.js.snap, src/Ml.Cli.WebApp/ClientApp/src/Comparison/TableResult.js, src/Ml.Cli.WebApp/ClientApp/src/Comparison/TableResult.scss, src/Ml.Cli.WebApp/ClientApp/src/Comparison/__snapshots__/index.spec.js.snap, src/Ml.Cli.WebApp/ClientApp/src/Tables/Paging.js, src/Ml.Cli.WebApp/ClientApp/src/Tables/Paging.spec.js
=> feat(pager): add top pager

src/Ml.Cli.WebApp/ClientApp/src/Annotation/Annotate.stories.js, src/Ml.Cli.WebApp/ClientApp/src/Comparison/TableResult.stories.js
=> Refactor(Storybook): update TableResult and Annotate components storybooks

README.md, src/Ml.Cli.WebApp/ClientApp/src/Comparison/StatsTable.js, src/Ml.Cli.WebApp/ClientApp/src/Comparison/__snapshots__/index.spec.js.snap, src/Ml.Cli.WebApp/ClientApp/src/Comparison/score.js, src/Ml.Cli.WebApp/ClientApp/src/Comparison/score.spec.js
=> feat(StatsFusion): add merge functionality to remove indexes from keys

src/Ml.Cli.WebApp/ClientApp/src/EnvironmentProvider.js, src/Ml.Cli.WebApp/ClientApp/src/FetchHelper.js
=> fix(EnvironmentProvider): remove "#" character from api route

demo/tasks-licenses.json, src/Ml.Cli.WebApp/ClientApp/package-lock.json, src/Ml.Cli.WebApp/ClientApp/package.json, src/Ml.Cli.WebApp/ClientApp/src/Annotation/AnnotationImagesLoader.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/NamedEntity/LabelV2Core.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/NamedEntity/Mark.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/NamedEntity/NamedEntity.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/NamedEntity/NamedEntity.scss, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/NamedEntity/NamedEntity.stories.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/NamedEntity/NamedEntityLazy.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/NamedEntity/TextAnnotation.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/NamedEntity/TokenAnnotator.scss, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/NamedEntity/labelColor.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Toolkit/NamedEntity/utils.js, src/Ml.Cli/JobDataset/Initializer.cs, src/Ml.Cli/JobDataset/README.MD
closes #100 
Un problème au niveau du component NamedEntity: le texte du bouton, "Soumettre l'annotation", est écrit en dur, donc intraductible en anglais
=> feat(Annotation): add NER component to toolkit

demo/tasks-licenses.json, src/Ml.Cli/JobDataset/README.MD
=> refactor(tasks): add tasks for all dataset types

src/Ml.Cli.WebApp/ClientApp/package-lock.json, src/Ml.Cli.WebApp/ClientApp/package.json, src/Ml.Cli.WebApp/ClientApp/src/Annotation/Annotate.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/AnnotationImagesLoader.js, src/Ml.Cli.WebApp/ClientApp/src/Annotation/__snapshots__/Annotate.spec.js.snap, src/Ml.Cli.WebApp/ClientApp/src/Comparison/Compare.js, src/Ml.Cli.WebApp/ClientApp/src/Comparison/JsonEditorTab.js, src/Ml.Cli.WebApp/ClientApp/src/Comparison/__snapshots__/index.spec.js.snap, src/Ml.Cli.WebApp/ClientApp/src/__snapshots__/Home.spec.js.snap
=> feat(Confirmation): add confirmation to annotation submission on Compare and Annotate pages

demo/tasks-licenses-docker-compose.json
=> feat(Annotation): add ImageClassifier component

azure-pipelines.yml
=> fix(Sonar): add js code coverage and exclude unit tests files and stories

.github/dependabot.yml
=> fix(Dependabot): update dependabot.yml to update package.json

src/Ml.Cli.WebApp/Local/Paths/BasePath.cs
=> fix(BasePath): BasePath verification now made properly

src/Ml.Cli.WebApp/ClientApp/src/Local/Gallery/Gallery.spec.js
=> test(Gallery): update test to remove warning of "not wrapped in act" state update

src/Ml.Cli.WebApp/ClientApp/src/Local/Annotation/Annotate.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Annotation/Annotate.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Annotation/Annotate.stories.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Annotation/AnnotationsContainer.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Annotation/AnnotationsContainer.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Annotation/DatasetHandler.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Annotation/DatasetHandler.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Annotation/Routes.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Comparison/Compare.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Comparison/ImagesLoader.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Comparison/JsonEditorTab.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Comparison/JsonEditorTab.stories.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Comparison/TableItem.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Comparison/TableItem.stories.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Comparison/TableResult.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Comparison/index.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Local/FetchHelper.js, src/Ml.Cli.WebApp/ClientApp/src/Local/FileLoader/FileLoader.js, src/Ml.Cli.WebApp/ClientApp/src/Local/FileTreatment/FileTreatment.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Gallery/Gallery.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Gallery/Gallery.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Gallery/Gallery.stories.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Home.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Library/Library.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Library/Library.spec.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Library/Library.stories.js, src/Ml.Cli.WebApp/ClientApp/src/Local/Routes.js
=> refactor(Fetch): rename all fetchFunction and mockedFetch occurences as fetch

src/Ml.Cli.WebApp/ClientApp/src/Toolkit/BoundingBox/Cropping.container.js, src/Ml.Cli.WebApp/ClientApp/src/Toolkit/BoundingBox/Labels.js
=> fix(cropping): label color and back

src/Ml.Cli.WebApp/ClientApp/src/Server/shared/Label/Label.js
=> refactor(Label): adapt label text color to its background
